// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	TELEGRAM_BOT_SESSIONS: KVNamespace;
	TEQTANK_API_BASE_URL: "https://api.teqtank.com";
}
